config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :items
	resources :baskets
	resources :basket_items
	resources :orders

	root "items#index"
end

app/models/basket.rb
# == Schema Information
#
# Table name: baskets
#
#  id          :integer          not null, primary key
#  checked_out :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Basket < ApplicationRecord
	has_many :basket_items, inverse_of: :basket, dependent: :destroy
	has_one :order


	has_many :items,      through: :basket_items, class_name: 'Item', source: :resource, source_type: "Item"
	has_many :promotions, through: :basket_items, class_name: 'Promotion', source: :resource, source_type: "Promotion"

	def items_total
		basket_items.items.reduce(0) { |sum, item| sum + (item.price * item.quantity) }
	end

	def calculate_product_discounts
		if added_promotion_item_ids && added_promotion_item_ids.size > 0
			discount = 0
			added_promotion_item_ids.each do |item_id|
				pi = PromotionItem.find_by_item_id(item_id)
				bi = basket_items.items.find_by_resource_id(item_id)

				times_apply = bi.quantity / pi.quantity

				discount += times_apply * (pi.quantity * bi.price - pi.value)
			end
			discount
		else
			0
		end
	end

	def added_promotion_item_ids
		promotion_items = PromotionItem.all.map(&:item_id)
		added_items = items.map(&:id)
		promotion_items & added_items
	end

	def number_of_items
		basket_items.items.map(&:quantity).reduce(:+)
	end

	def calculate_amount_discounts
		promotions.amounts.map(&:value).reduce(:+) || 0
	end


	def total_with_promotions

		subtotal = items_total - calculate_product_discounts - calculate_amount_discounts
		if subtotal < 0
			BigDecimal.new('0.1')
		else
			promotions.percents.map(&:value).reduce(subtotal) { |sum, el| sum * (1 - el / 100) }
		end
	end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
	def index
		if current_basket.persisted?
			redirect_to basket_path(current_basket.id)
		else
			render 'empty'
		end
	end

	def show
		@basket = current_basket
	end

	def destroy
		@basket = current_basket
		if @basket.destroy
			flash[:notice] = "Basket cleared"
			redirect_to baskets_path
		else
			flash[:alert] = "Error: could not clear the basket"
		end
	end
end

app/views/baskets/empty.html.erb
<div class='container'>
	<h2> Your basket is empty. Add some items </h2>
</div>

app/views/baskets/show.html.erb
<%= toast %>

<div class='container'>
  <h2>Your Basket</h2>

  <%= form_for(@basket.basket_items.new, remote: true) do |f| %>
    <%= f.hidden_field :basket_id, value: @basket.id %>
    <%= f.hidden_field :resource_type, value: 'Promotion' %>
    <div class='row mb-2'>
      <div class="col col-4">
        <%= f.text_field :promo_code, placeholder: 'Enter your promo code', class: 'form-control', type: "text" %>
      </div>
      <div class='col col-2'>
        <%= f.submit "Add promo code", class: 'btn btn-primary btn-sm' %>
      </div>
    </div>
  <% end %>

  <table class='table table-bordered table-hover table-striped table-sm'>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Unit Price</th>
      <th>Cost</th>
      <th></th>
    </tr>

  <% @basket.basket_items.items.each do |basket_item| %>
    <tr>
      <td><%= basket_item.name %></td>
      <td>
        <%= form_for basket_item do |f| %>
          <div class='row'>
            <div class="col col-6">
              <%= f.text_field :quantity, min: 1, class: 'form-control', type: "number" %>
            </div>
            <div class='col col-6'>
              <%= f.submit "Save", class: 'btn btn-outline-primary btn-sm' %>
            </div>
          </div>

        <% end %>
      </td>

      <td><%= number_to_currency(basket_item.price, unit: "£") %></td>
      <td><%= number_to_currency(basket_item.price * basket_item.quantity, unit: "£") %></td>
      <td><%= button_to "X", basket_item, method: :delete, class: 'btn btn-outline-danger' %></td>
    </tr>
  <% end %>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td class='font-weight-bold'><%= number_to_currency(@basket.items_total, unit: "£") %></td>
      <td></td>
    </tr>
    <tr></tr>
  <% @basket.basket_items.promotions.each do |basket_item| %>
    <tr class='table-info'>
      <td><%= basket_item.resource.code %></td>
      <td><%= basket_item.quantity %></td>
      <td></td>
      <td>-<%= basket_item.resource.kind == 'percent' ? "#{basket_item.resource.value.to_i}%" : number_to_currency(basket_item.resource.value, unit: "£") %></td>
      <td><%= button_to "X", basket_item, method: :delete, class: 'btn btn-outline-danger' %></td>
    </tr>
  <% end %>
  </table>

  <div>
    <%= link_to "Check out", new_order_path, class: 'btn btn-success' %>
    <%= link_to "Clear ", basket_path(@basket), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>

  </div>
  <br>
</div>